# Generated by Django 5.1.4 on 2024-12-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
